# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Equity Scrape of NASDAQ

on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 19 5 *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run Equity Scrape
      run: |
        python equity_scrape.py
    - name: Setup Github Config
      run: |
        git config --global user.name "shanthisai"
        git config --global user.email "shanthisai07@msitprogram.net"
    - name: Commiting New Files
      run: |
          git pull origin master
          git add *
          git commit -m "`date +'%d-%m-%Y'`"
          git push origin master     
    
